---

- name: Check for emtpy pmm_server_username and pmm_server_password
  fail: msg="Username or pmm_server_password cannot be empty while enabling pmm_server_password protection"
  when: ( pmm_server_username == '' )  or ( pmm_server_password == '' )


- name: Running PMM Data Container secured with pmm_server_username and pmm_server_password
  docker_container:
    name: pmm-server
    image: "percona/pmm-server:{{ pmm_server_version }}"
    state: started
    cpu_period: "{{ pmm_server_docker_cpu_period }}"
    cpu_quota: "{{ pmm_server_docker_cpu_quota }}"
    memory: "{{ pmm_server_docker_memory }}"
    memory_reservation: "{{ pmm_server_docker_memory_reservation }}"
    purge_networks: "{{ pmm_server_docker_purge_networks }}"
    networks: "{{ pmm_server_docker_networks }}"
    volumes:
    - /etc/grafana:/etc/grafana
    volumes_from:
    - pmm-data
    env: "{{ __pmm_server_env }}"
    ports:
    - "{{ pmm_server_http_port }}:80"
    restart_policy: always
